#  你可以运行多个jobs。默认情况下，这些jobs是平行地运行的。

name: parallel-jobs
on:
  push:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "干活"
  job-b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "干更多的活"
