# 你可以通过编写“工作流(workflow)”来配置GitHub Actions。
# 工作流(Workflows)定义了一系列使用[YAML](http://ruanyifeng.com/blog/2016/07/yaml.html)书写的命令
# 配置文件必须位于仓库根目录的 `.github/workflows/` 目录下。
# ::newline
# 这个actions样例按照"Hello world"->"Step 1...", "Step 2...", "Step 3..."->"Goodbye"的顺序输出.

name: hello-world-example

# ::span-comment
# 我们必须明确什么条件或行为会触发工作流。
# 在这个例子里，只要发生“向仓库推送”的行为，就会触发此工作流。
on:
  push:
# ::end-span

jobs:
  # `job` 明确一系列将要执行的命令。
  # 我们将这个job命名为`say-hello`.
  say-hello:
    # `job`可以在不同计算机运行[所有计算机类型](https://docs.github.com/zh/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on).
    runs-on: ubuntu-latest
    # `steps` 是一系列将要运行的命令
    steps:
      -
        name: Say Hello
        # 使用目标计算机的shell运行`echo`命令，输出"Hello world!"
        run: echo "Hello world!"
      -
        name: Do stuff
        # ::span-comment
        # 使用通道 `|` 来作为yaml中可换行的字符串的开始。这将会增加我们代码的可读性。
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
        # ::end-span
      -
        name: Say Goodbye
        run: echo "Goodbye!"
